### ISSUE TITLE
表現の不一致

### ISSUE THREAD

**Issue by yoshihiro0323** [miko-misa/programming-tutorial#1]
「プリミティブ型」という表現を使うならオブジェクト型、「参照型」という表現を使うなら「値型」にしたほうがいいと思います。
「プリミティブ型（値型）」「オブジェクト型（参照型）」と両方の表現を使ってあげると親切かも？

**Comment by miko-misa** [comment]
値型ってあんま使われんしたぶんプリミティブ型と参照型の対比はJavaでよく使われると思う.

**Comment by yoshihiro0323** [comment]
Java以外にも配慮しろ()

**Comment by miko-misa** [comment]
いや言語によって様々な言い方があるからもっともスタンダードなJavaで考えるべきでは？
