### ISSUE TITLE
第２章　誤字など

### ISSUE THREAD

**Issue by HornCake** [miko-misa/programming-tutorial#2]
「各言語の片付け」になってるが、正しくは「各言語の型付け」だと思われる

**Comment by HornCake** [comment]
追加誤字
- 2.5 Java は {} 単体でもブロックをブロックスコープについてのコードを見てください.
文意がよみとれない.
- 2.8.2 x y|
ビットORの演算子の位置が誤っている

**Comment by miko-misa** [comment]
thx
