### ISSUE TITLE
Javaのコードで;が:になっている

### ISSUE THREAD

**Issue by HornCake** [miko-misa/programming-tutorial#3]
フォントのせい？

**Comment by HornCake** [comment]
;を使用する全言語でなってるかも

**Comment by HornCake** [comment]
![image](https://github.com/miko-misa/programming-tutorial/assets/53281552/052888c4-3d0b-4d98-a9e3-05de006635d6)
フォントのせいか環境のせいか
(コードはちゃんと;になってたね)

**Comment by miko-misa** [comment]
ホントだ。なんでやこれ。

**Comment by miko-misa** [comment]
@HornCake バカしてました。ありがとう。
